apiVersion : apps/v1
kind: Deployment
metadata:
  name: "-58c2"
spec:
  selector:
    matchLabels: "-58c2"
      app: ""
  replicas: 2
  template:
    metadata:
      labels:
        app: "-58c2"
    spec:
      containers:
        - name: "-58c2"
          image: "diaggarwtest.azurecr.io/1439"
          ports:
          - containerPort: {&quot;port&quot;:&quot;8080&quot;,&quot;protocol&quot;:&quot;tcp&quot;}
