apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaaatiwarishubaks-0326"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaaatiwarishubaks-0326"
  template:
    metadata:
      labels:
        app: "aaaaatiwarishubaks-0326"
    spec:
      containers:
        - name: "aaaaatiwarishubaks-0326"
          image: "diaggarwregistry.azurecr.io/aaaaatiwarishubaks5398"
          ports:
          - containerPort: 8080