apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaaatiwarishubaks-c160"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaaatiwarishubaks-c160"
  template:
    metadata:
      labels:
        app: "aaaaatiwarishubaks-c160"
    spec:
      containers:
        - name: "aaaaatiwarishubaks-c160"
          image: "aaaaatiwarishubaks12.azurecr.io/aaaaatiwarishubaks0f0d"
          ports:
          - containerPort: 8080