apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaaatiwarishubaks-8741"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaaatiwarishubaks-8741"
  template:
    metadata:
      labels:
        app: "aaaaatiwarishubaks-8741"
    spec:
      containers:
        - name: "aaaaatiwarishubaks-8741"
          image: "diaggarwregistry.azurecr.io/aaaaatiwarishubaksc34b"
          ports:
          - containerPort: 8080