apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaaatiwarishubaks-0d23"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaaatiwarishubaks-0d23"
  template:
    metadata:
      labels:
        app: "aaaaatiwarishubaks-0d23"
    spec:
      containers:
        - name: "aaaaatiwarishubaks-0d23"
          image: "diaggarwregistry.azurecr.io/aaaaatiwarishubaks356f"
          ports:
          - containerPort: 8080