apiVersion : apps/v1
kind: Deployment
metadata:
  name: "-1a03"
spec:
  selector:
    matchLabels: "-1a03"
      app: ""
  replicas: 2
  template:
    metadata:
      labels:
        app: "-1a03"
    spec:
      containers:
        - name: "-1a03"
          image: "diaggarwtest.azurecr.io/ca5c"
          ports:
          - containerPort: {&quot;port&quot;:&quot;8080&quot;,&quot;protocol&quot;:&quot;tcp&quot;}
