apiVersion: v1
kind: Service
metadata:
    name: "diaggarw-bb00"
    labels:
        app: "diaggarw-bb00"
spec:
    type: ClusterIP
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "diaggarw-bb00"
