apiVersion: v1
kind: Service
metadata:
    name: "aaaaatiwarishubaks-c69e"
    labels:
        app: "aaaaatiwarishubaks-c69e"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "aaaaatiwarishubaks-c69e"