on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_GITHUB_SECRET}}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n tiwarishubACRN1 -g tiwarishubACRN165 --location "South Central US" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n tiwarishubACRN1 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n tiwarishubACRN1 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n tiwarishubACRN1 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: tiwarishubacrn1.azurecr.io
        username: ${{steps.create-acr.outputs.acr_username}}
        password: ${{steps.create-acr.outputs.acr_password}}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t tiwarishubacrn1.azurecr.io/aaaaatiwarishubaksdc6d:${{github.sha}}
        docker push tiwarishubacrn1.azurecr.io/aaaaatiwarishubaksdc6d:${{github.sha}}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{secrets.aks_aaaaatiwarishubaks_kubeConfig}}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aaaaatiwarishubaks1121 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aaaaatiwarishubaks1121`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aaaaatiwarishubaks1121
        container-registry-url: tiwarishubacrn1.azurecr.io
        container-registry-username: ${{steps.create-acr.outputs.acr_username}}
        container-registry-password: ${{steps.create-acr.outputs.acr_password}}
        secret-name: aaaaatiwarisdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: aaaaatiwarishubaks1121
        manifests: |
          manifests/deployment-b261.yml
          manifests/service-b261.yml
        images: |
          tiwarishubacrn1.azurecr.io/aaaaatiwarishubaksdc6d:${{github.sha}}
        imagepullsecrets: |
          aaaaatiwarisdockerauth